name: task
version: 1.1.1+11
publish_to: none
description: A new Flutter project.
environment:
  sdk: ^3.5.0

dependencies:
  #字符串处理
  characters: ^1.3.0
  #数据处理
  collection: ^1.18.0
  cupertino_icons: ^1.0.8
  #设备信息
  device_info_plus: ^11.1.0
  #网络请求
  dio: ^5.7.0
  #escpos工具
  esc_pos_utils_plus: ^2.0.4
  #escpos连接
  flutter_esc_pos_network: ^1.0.3
  flutter:
    sdk: flutter
  #移动端后台服务
  flutter_background_service: ^5.0.10
  #Android后台服务
  flutter_background_service_android: ^6.2.7
  #对话提示工具
  flutter_easyloading: ^3.0.5
  #webview
  flutter_inappwebview: ^6.1.5
  #本地化
  flutter_localizations:
    sdk: flutter
  #状态管理
  get: ^4.6.6
  #本地存储
  get_storage: ^2.1.1
  #图片处理
  image: ^4.3.0
  #国际化
  intl: ^0.19.0
  #日志
  logger: ^2.4.0
  #路径
  path_provider: ^2.1.4
  #二维码
  qr_flutter: ^4.1.0
  #托盘
  tray_manager: ^0.2.4
  #windows
  win32: ^5.6.0
  #交错动画
  flutter_staggered_animations: ^1.1.1
dev_dependencies:
  flutter_launcher_icons: ^0.14.1
  flutter_lints: ^5.0.0
  flutter_native_splash: ^2.4.1
  flutter_test:
    sdk: flutter
  msix: ^3.16.8

#启动图标配置
flutter_icons:
  android: "launcher_icon"
  ios: true
  windows:
    generate: true
    image_path: "assets/icon.png"
    background_color: "#FFFFFF"
    theme_color: "#FFFFFF"
  image_path: "assets/icon.png"
  min_sdk_android: 21 # android min sdk min:16, default 21
  adaptive_icon_background: "#6A3DE8"
  adaptive_icon_foreground: "assets/icon.png"
  remove_alpha_ios: true

#启动图配置
flutter_native_splash:
  android: true
  ios: true
  web: false
  #windows: true
  image: assets/launcher.png
  color_dark: "#6A3DE8"
  fullscreen: true
  color: "#022200"
  android_12:
    color: "#6A3DE8"
    image: assets/launcher.png
    color_dark: "#6A3DE8"
  android_gravity: center
  ios_content_mode: center

#msix配置
msix_config:
  display_name: Task
  identity_name: net.pericles.task
  msix_version: 1.0.0.2
  certificate_path: C:\certificate\certificate.pfx
  certificate_password: 123456
  capabilities: internetClient,Escpos
  logo_path: D:\project\FlutterProject\task\windows\runner\resources\app_icon.ico
  execution_alias: task
  enable_at_startup: true

flutter:
  uses-material-design: true
  assets:
    - assets/
