name: task
version: 1.0.1+1
publish_to: none
description: A new Flutter project.
environment:
  sdk: ^3.5.0

dependencies:
  cupertino_icons: ^1.0.8
  get: 4.6.6
  flutter:
    sdk: flutter
  flutter_easyloading: ^3.0.5
  get_storage: ^2.1.1
  intl: ^0.19.0
  dio: ^5.6.0
  characters: ^1.3.0
  logger: ^2.4.0
  flutter_localizations:
    sdk: flutter
  esc_pos_printer: ^4.1.0
  esc_pos_utils: ^1.1.0
  image: ^3.3.0
  collection: ^1.18.0
  qr_flutter: ^4.1.0
  path_provider: ^2.1.4
  flutter_launcher_icons: ^0.11.0
  flutter_native_splash: ^2.2.16
  flutter_background_service: ^5.0.10
  flutter_background_service_android: ^6.2.7
  webview_flutter: ^4.9.0
  device_info_plus: ^10.1.2

flutter_icons:
  android: "launcher_icon"
  ios: true
  windows:
    generate: true
    image_path: "assets/icon.png"
    background_color: "#FFFFFF"
    theme_color: "#FFFFFF"
  image_path: "assets/icon.png"
  min_sdk_android: 21 # android min sdk min:16, default 21
  adaptive_icon_background: "#6A3DE8"
  adaptive_icon_foreground: "assets/icon.png"
  remove_alpha_ios: true

flutter_native_splash:
  android: true
  ios: true
  web: false
  windows: true
  image: assets/launcher.png
  color_dark: "#6A3DE8"
  fullscreen: true
  color: "#022200"
  android_12:
    color: "#6A3DE8"
    image: assets/launcher.png
    color_dark: "#6A3DE8"
  android_gravity: center
  ios_content_mode: center
msix_config:
  display_name: Task
  msix_version: 1.0.0.0
  certificate_path: C:/flutter_windows_cer/CERTIFICATE.pfx
  certificate_password: 123456
  logo_path: E:/Project/FlutterProject/task/assets/icon.png
  build_path: build/windows/x64/runner/Release

assets:
  - assets/

dev_dependencies:
  flutter_lints: 4.0.0
  flutter_test:
    sdk: flutter
  msix: ^3.7.0

flutter:
  uses-material-design: true
